# Generated by Django 5.2.4 on 2025-09-25 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_limbu', models.CharField(blank=True, help_text='Lesson name in Limbu', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/images/')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Lesson description in English')),
                ('description_limbu', models.TextField(blank=True, help_text='Lesson description in Limbu')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_image', models.ImageField(help_text='Image of the subject being taught', upload_to='questions/images/')),
                ('subject_name_english', models.CharField(help_text='What the image shows in English', max_length=100)),
                ('subject_name_limbu', models.CharField(help_text='What the image shows in Limbu (displayed under image)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Question order in the lesson')),
                ('points', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.lessons')),
            ],
            options={
                'ordering': ['lesson', 'order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text_english', models.CharField(help_text='Option in English', max_length=200)),
                ('option_text_limbu', models.CharField(help_text='Option in Limbu', max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(help_text='Option order (1-10)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.question')),
            ],
            options={
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('language_mode', models.CharField(choices=[('english', 'English'), ('limbu', 'Limbu')], default='english', help_text='Language mode when answered', max_length=10)),
                ('time_taken', models.PositiveIntegerField(blank=True, help_text='Time taken to answer in seconds', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('selected_option', models.ForeignKey(help_text='Which option the user selected', on_delete=django.db.models.deletion.CASCADE, to='api.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_english', models.CharField(max_length=200)),
                ('word_limbu', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text="e.g., 'animals', 'food', 'colors'", max_length=100)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='api.lessons')),
            ],
            options={
                'ordering': ['word_english'],
                'unique_together': {('word_english', 'word_limbu')},
            },
        ),
    ]
