# Generated by Django 5.2.4 on 2025-09-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='description_limbu',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject_name_limbu',
        ),
    ]
